// src/components/TutorBot.vue
<template>
  <div class="tutor-bot" v-if="showAnswer">
    <button @click="toggleExplanation" class="why-button">
      {{ explanationVisible ? '✕ Hide' : '💡 Why?' }}
    </button>
    
    <div v-if="explanationVisible" class="explanation-panel">
      <div v-if="loading" class="loading">
        <p>Generating explanation...</p>
      </div>
      <div v-else-if="explanation" class="explanation-content">
        <p>{{ explanation }}</p>
        <div class="explanation-source">
          {{ isPaid ? '📚 Premium Explanation' : '💡 Free Explanation' }}
        </div>
      </div>
      <div v-else class="error">
        Unable to generate explanation. Try again?
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue';
import { generateExplanation } from '../utils/tutorBot';

const props = defineProps({
  question: String,
  userAnswer: String,
  correctAnswer: String,
  showAnswer: Boolean,
  isPaid: { type: Boolean, default: false }
});

const explanationVisible = ref(false);
const explanation = ref('');
const loading = ref(false);

const toggleExplanation = async () => {
  if (explanationVisible.value) {
    explanationVisible.value = false;
  } else {
    explanationVisible.value = true;
    if (!explanation.value) {
      loading.value = true;
      explanation.value = await generateExplanation(
        props.question,
        props.userAnswer,
        props.correctAnswer,
        props.isPaid
      );
      loading.value = false;
    }
  }
};
</script>

<style scoped>
.tutor-bot {
  margin-top: 1rem;
}

.why-button {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  border: none;
  padding: 0.75rem 1.5rem;
  border-radius: 8px;
  cursor: pointer;
  font-weight: 600;
  transition: all 0.3s;
}

.why-button:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(102, 126, 234, 0.4);
}

.explanation-panel {
  margin-top: 1rem;
  padding: 1.5rem;
  background: linear-gradient(135deg, rgba(102, 126, 234, 0.1) 0%, rgba(118, 75, 162, 0.1) 100%);
  border-left: 4px solid #667eea;
  border-radius: 8px;
}

.loading {
  text-align: center;
  color: #667eea;
  font-style: italic;
}

.explanation-content {
  color: #333;
  line-height: 1.6;
}

.explanation-source {
  margin-top: 0.75rem;
  font-size: 0.85rem;
  color: #999;
  text-align: right;
}

.error {
  color: #e74c3c;
  text-align: center;
}
</style>

// src/components/TutorBot.jsx
import { useState } from 'react';
import { generateExplanation } from '../utils/tutorBot';

export const TutorBot = ({ question, userAnswer, correctAnswer, showAnswer, isPaid = false }) => {
  const [explanationVisible, setExplanationVisible] = useState(false);
  const [explanation, setExplanation] = useState('');
  const [loading, setLoading] = useState(false);

  const toggleExplanation = async () => {
    try {
      if (explanationVisible) {
        setExplanationVisible(false);
      } else {
        setExplanationVisible(true);
        if (!explanation) {
          setLoading(true);
          try {
            const result = await generateExplanation(
              question, 
              userAnswer, 
              correctAnswer, 
              isPaid,
              (chunk) => {
                // Stream callback - update explanation as chunks arrive
                setExplanation(chunk || '');
              }
            );
            setExplanation(result || 'No explanation available');
          } catch (err) {
            console.error('TutorBot generation error:', err);
            setExplanation('Explanation temporarily unavailable. Try again?');
          }
          setLoading(false);
        }
      }
    } catch (err) {
      console.error('TutorBot error:', err);
      setLoading(false);
    }
  };

  if (!showAnswer) return null;

  return (
    <div className="tutor-bot">
      <button
        onClick={toggleExplanation}
        className="why-button"
        style={{
          background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
          color: 'white',
          border: 'none',
          padding: '0.75rem 1.5rem',
          borderRadius: '8px',
          cursor: 'pointer',
          fontWeight: '600',
          transition: 'all 0.3s',
          marginTop: '1rem'
        }}
        onMouseEnter={(e) => {
          e.target.style.transform = 'translateY(-2px)';
          e.target.style.boxShadow = '0 4px 12px rgba(102, 126, 234, 0.4)';
        }}
        onMouseLeave={(e) => {
          e.target.style.transform = 'translateY(0)';
          e.target.style.boxShadow = 'none';
        }}
      >
        {explanationVisible ? '✕ Hide' : '💡 Why?'}
      </button>

      {explanationVisible && (
        <div
          style={{
            marginTop: '1rem',
            padding: '1.5rem',
            background: 'linear-gradient(135deg, rgba(102, 126, 234, 0.1) 0%, rgba(118, 75, 162, 0.1) 100%)',
            borderLeft: '4px solid #667eea',
            borderRadius: '8px'
          }}
        >
          {loading && (
            <div style={{ textAlign: 'center', color: '#667eea', fontStyle: 'italic' }}>
              <p>Generating explanation...</p>
            </div>
          )}
          {!loading && explanation && (
            <div style={{ color: '#e8eef9', lineHeight: '1.6' }}>
              <p style={{ fontSize: '0.95rem' }}>{explanation}</p>
              <div style={{ marginTop: '0.75rem', fontSize: '0.85rem', color: '#a8b5d1', textAlign: 'right' }}>
                {isPaid ? '📚 Premium Explanation' : '💡 Free Explanation (Ollama)'}
              </div>
            </div>
          )}
          {!loading && !explanation && (
            <div style={{ color: '#e74c3c', textAlign: 'center' }}>
              Unable to generate explanation. Try again?
            </div>
          )}
        </div>
      )}
    </div>
  );
};
